// Built-in domain lists for Opal's category tokens.
// These mirror the categories Opal uses on its supported browsers.
const CATEGORY_DOMAINS = {
  social: [
    "facebook.com", "messenger.com",
    "twitter.com", "x.com",
    "instagram.com",
    "reddit.com",
    "tiktok.com",
    "snapchat.com",
    "linkedin.com",
    "pinterest.com",
    "tumblr.com",
    "discord.com",
    "threads.net",
    "mastodon.social",
    "bsky.app",
    "bereal.com",
    "vk.com",
    "weibo.com",
  ],
  video: [
    "youtube.com", "youtu.be", "googlevideo.com",
    "netflix.com",
    "twitch.tv",
    "hulu.com",
    "disneyplus.com",
    "max.com", "hbomax.com",
    "primevideo.com",
    "paramountplus.com",
    "peacocktv.com",
    "vimeo.com",
    "dailymotion.com",
    "rumble.com",
    "kick.com",
    "odysee.com",
    "crunchyroll.com",
    "funimation.com",
    "bilibili.com",
    "pluto.tv",
    "tubi.tv",
  ],
  news: [
    "cnn.com",
    "bbc.com", "bbc.co.uk",
    "nytimes.com",
    "washingtonpost.com",
    "theguardian.com",
    "foxnews.com",
    "huffpost.com",
    "buzzfeed.com",
    "dailymail.co.uk",
    "reuters.com",
    "apnews.com",
    "nbcnews.com",
    "cbsnews.com",
    "usatoday.com",
    "msn.com",
    "bloomberg.com",
    "wsj.com",
    "ft.com",
    "economist.com",
    "vox.com",
    "theatlantic.com",
    "politico.com",
    "axios.com",
    "thehill.com",
    "spiegel.de",
    "zeit.de",
    "sueddeutsche.de",
    "lemonde.fr",
    "lefigaro.fr",
    "elpais.com",
  ],
  gambling: [
    "draftkings.com",
    "fanduel.com",
    "betmgm.com",
    "caesarssportsbook.com",
    "bet365.com",
    "williamhill.com",
    "ladbrokes.com",
    "betway.com",
    "unibet.com",
    "bwin.com",
    "pokerstars.com",
    "partypoker.com",
    "888casino.com",
    "pointsbet.com",
    "bovada.lv",
    "mybookie.ag",
    "betonline.ag",
  ],
  dating: [
    "tinder.com",
    "bumble.com",
    "okcupid.com",
    "match.com",
    "hinge.co",
    "pof.com",
    "eharmony.com",
    "zoosk.com",
    "coffeemeetsbagel.com",
    "grindr.com",
    "scruff.com",
    "feeld.co",
    "badoo.com",
    "happn.com",
    "hily.com",
  ],
  adult: [
    "pornhub.com",
    "xvideos.com",
    "xnxx.com",
    "redtube.com",
    "youporn.com",
    "xhamster.com",
    "spankbang.com",
    "tube8.com",
    "onlyfans.com",
    "fansly.com",
    "brazzers.com",
    "playboy.com",
  ],
};
